const Constants = {
  DIFF_ACC: 'DIFF_ACC',
  MONTHS: 'Months',
  WINEER_DATES: 'Winner_dates',
  APP_VERSION: 'app_version',
  OTP_TYPE_VOICE: 'Voice',
  PROFESSION: 'PROFESSION',
  BANKS: 'BANKS',
  LOGIN_OTP_USER_NAME: 'login_otp_user_name',
  IS_LOGIN_WITH_OTP: 'login_with_otp',
  LOGIN_TYPE_PASS: 'password',
  LOGIN_TYPE_OTP: 'otp',
  RET_USER_TYPE: '2',
  INF_USER_TYPE: '1',
  EC_SUB_USER_TYPE: 'electrical',
  AC_SUB_USER_TYPE: 'ac_sub_user',
  RET_SUB_USER_TYPE: 'ret_sub_user',
  AIR_COOLER_ENABLED: '1',
  AIR_COOLER_DISABLED: '0',
  CONTACT_US: 'contact_us',
  ID_TYPES: 'id_types',
  NOTIFICATION: 'NOTIFICATION',
  KEY_USER_REFRESH_REQ: 'user_refreshreq',
  SORT_POINTS_LOW_TO_HIGH: 'Points low to high',
  SORT_POINTS_HIGH_TO_LOW: 'Points high to low',
  CREDS: 'creds',
  KEY_USER: 'key_user',
  KEY_USER_CREDS: 'key_user_creds',
  KEY_RISHTA_USER: 'key_rishta_user',
  HOME_FRAGMENT: 'HomeFragment',
  USER_VERIFICATION: 'UserVerification',
  DASHBOARD_FRAGMENT: 'DashboardFragment',
  LOGIN_WITH_OTP_FRAGMENT: 'LoginWithOtpFragment',
  FORGOT_PASSWORD_FRAGMENT: 'ForgotPasswordFragment',
  PRODUCT_CATEGORY_FRAGMENT: 'ProductCategoryFragment',
  RETAILER: 'DIS',
  MECHANIC: 'RET',
  CUSTOMER: 'CUST',
  UNO_MINDA_CARE: 'ASC',
  INDEPENDENT_WORKSHOP: 'IWS',
  HEAD_MANAGER: 'HO',
  REGIONAL_MANAGER: 'ZO',
  BRANCH_MANAGER: 'RO',
  TERRITORY_MANAGER: 'APM',
  DISTRIBUTOR: 'DIST',
  GROWTH_OFFICER: 'GO',
  CITY: 'city',
  USERS: 'users',
  STATES: 'state',
  CATEGORY: 'category',
  DISTRICT: 'districtName',
  TICKET_TYPE: 'ticketType',
  SORT: 'sort',
  USER_OBJECT: 'userObject',
  PRODUCT_CATEGORY: 'productCategory',
  PRODUCT_CATEGORY_NAME: 'productCategoryName',
  PACK_CATEGORY_ID: 'packCategoryId',
  PACK_CATEGORY_NAME: 'packCategoryName',
  SELECTED_SEGMENT: 'selected_segment',
  PRODUCT: 'product',
  USER_TYPE: 'UserType',
  USER_ROLE: 'USER_ROLE',
  ORDER: 'ORDER',
  CHEQUE: 'CHEQUE',
  ID_CARD_FRONT: 'ID_CARD_FRONT',
  TICKET: 'TICKET',
  ID_CARD_BACK: 'ID_CARD_BACK',
  PAN_CARD_FRONT: 'PAN_CARD_FRONT',
  PAN_CARD_BACK: 'PAN_CARD_BACK',
  ERROR_COUPON: 'ERROR_COUPON',
  WARRANTY: 'WARRANTY',
  BILL: 'BILL',
  GST: 'GST',
  PROFILE: 'PROFILE',
  WORKSHOP: 'WORKSHOP',
  INVOICE: 'INVOICE',
  DISPLAY_CONTEST: 'DISPLAY_CONTEST',
  CASH: 'CASH',
  PAYTM: 'PAYTM',
  GIFT: 'Bank Card',
  COUPON: 'Gift Vouchers',
  BANK_GIFT_CARD: 'Bank Gift Card',
  IMAGE_RELATED: 'image_related',
  RESULT_OK: 1,
  PDF: 'terms.pdf',
  USER_LIST: 'userList',
  UPLOAD_ORDER: 'UPLOAD_ORDER',
  INVOICE_DETAILS: 'INVOICE_DETAILS',
  IS_RETAILER_COUPON: 'is_retailer_coupon',
  RETAILER_FULL_NAME: 'Retailer',
  VEHICLE_SEGMENT: 'vehicle_segment',
  HOME_SCREEN: 'HOME',
  REDEMPTION_SCREEN: 'REDEMPTION',
  AIR_COOLER_OFFER: '6',
  AIRCOOLER_SCREEN: '1',
};
export const Colors = {
  colorPrimary: '#F0C300',
  colorPrimaryDark: '#F0C300',
  primary_light: '#f9e799',
  colorAccent: '#2cb0e1',
  primary_text: '#212121',
  text: '#5C5B5B',
  secondary_text: '#757575',
  white: '#FFFFFF',
  black: '#000104',
  red: '#FF0000',
  coupon_page: '#7798e9',
  grey_light: '#BDBDBD',
  activity_bg_color: '#FFFFFF',
  yellow: '#F0C300',
  transparent_white: '#00FFFFFF',
  custom_black: '#000104',
  grey: '#9E9E9E',
  grey_400: '#BDBDBD',
  login_box_divider: '#B7BDBDBD',
  blue: '#3F51B5',
  white_translucent: '#70ffffff',
};

export const baseUrl = 'http://34.100.133.239:18092/vguard/api/';
export const imageUrl = 'https://vguardrishta.com/';

export default Constants;
